#!/usr/bin/env node
/**
 * generate-sw.js
 * Runs automatically via the "postbuild" npm script after `next build`.
 *
 * What it does:
 *   1. Reads the Next.js build output in .next/static/ to find every
 *      JS chunk, CSS file, and font generated by the build.
 *   2. Builds a full list of /_next/static/... URLs.
 *   3. Injects those URLs into scripts/sw-template.js (replacing the
 *      BUILD_ASSETS_PLACEHOLDER comment).
 *   4. Writes the result to public/sw.js.
 *
 * The resulting service worker pre-caches ALL app assets at install time,
 * so the PWA works fully offline immediately after first install — even
 * for pages the user has never visited.
 */

const fs   = require('fs');
const path = require('path');

const ROOT        = process.cwd();
const STATIC_DIR  = path.join(ROOT, '.next', 'static');
const TEMPLATE    = path.join(ROOT, 'scripts', 'sw-template.js');
const OUTPUT      = path.join(ROOT, 'public', 'sw.js');
const PLACEHOLDER = '  // BUILD_ASSETS_PLACEHOLDER';

// Recursively collect every JS, CSS, and web-font file under a directory.
// Returns URL-path strings like /_next/static/chunks/main-abc123.js
function collectAssets(dir, urlPrefix) {
  const results = [];
  let entries;
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return results; // directory doesn't exist — skip silently
  }
  for (const entry of entries) {
    const childDir = path.join(dir, entry.name);
    const childUrl = `${urlPrefix}/${entry.name}`;
    if (entry.isDirectory()) {
      results.push(...collectAssets(childDir, childUrl));
    } else if (/\.(js|css|woff2?)$/.test(entry.name)) {
      results.push(childUrl);
    }
  }
  return results;
}

// Read template
let template;
try {
  template = fs.readFileSync(TEMPLATE, 'utf8');
} catch (err) {
  console.error('[generate-sw] ✗ Could not read template:', err.message);
  process.exit(1);
}

// Collect build assets
const buildAssets = collectAssets(STATIC_DIR, '/_next/static');

if (buildAssets.length === 0) {
  console.warn('[generate-sw] ⚠ No build assets found — is this running after `next build`?');
} else {
  console.log(`[generate-sw] Found ${buildAssets.length} build assets to pre-cache.`);
}

// Inject into template
const injectedLines = buildAssets.map((url) => `  '${url}',`).join('\n');
const output = template.replace(PLACEHOLDER, injectedLines);

// Write public/sw.js
try {
  fs.writeFileSync(OUTPUT, output, 'utf8');
  console.log('[generate-sw] ✓ public/sw.js generated successfully.');
  console.log(`[generate-sw]   Pre-caching ${5 + buildAssets.length} total assets (5 core + ${buildAssets.length} build).`);
} catch (err) {
  console.error('[generate-sw] ✗ Could not write public/sw.js:', err.message);
  process.exit(1);
}
